### PR TITLE
Run app on system startup and backup/restore user interface

### PR DESCRIPTION
**Pull request by ayell**
In this PR , i run the app on startup and  zip / unzip Interface/WTF folder to backup

### CODE REVIEW

**Comment by KevinAllenWiegand** [comment]
That's a lot of files with nothing but whitespace changes.

**Comment by ayell** [comment]
I know ... I'm working on Linux and a I use 2 tabs on text format :/

**Comment by jliddev** [comment]
Can you tell which files might be relevent? dont want to scroll down 150 pages of line changes lol

**Comment by KevinAllenWiegand** [comment]
> Can you tell which files might be relevent? dont want to scroll down 150 pages of line changes lol

Hot tub UI...you can choose to "ignore whitespace".  As for the author...you should probably change your IDE settings to match the tabbing/spaces of the project to avoid this.

**Comment by ayell** [comment]
I fix the conflits and my dev environment :)

I would like continue this feature whith a new windows to manage old backup and set a link to custom cloud provider ( google drive/dropbox) . How can I contact u for have more explains how u want I create a new windows properly ? 

Thank

**Comment by jliddev** [comment]
This one is difficult as we are primarily focused on getting 2.0 out and slowing any merges into the existing 1.19 beta. If you're invested feel free to look into a PR for 2.0 off the electron branch.

**Comment by ayell** [comment]
No problem , i'm more comfortable in JS than C#

**Pull request closed without merging**
