### PR TITLE
[electron] Backup/Restore addons & user interface

### PR DESCRIPTION
**Pull request by ayell**
In this PR I save/restore the addons as well as the interface.

I use adm-zip to do this and it blocks the main thread and I don't have the snackbar displayed. I made a setTimeout to counter this but if someone has a more elegant solution to run this in the background.

I've added the translations for en and fr

Tested on Linux and Windows

### CODE REVIEW

**Comment by jliddev** [comment]
I'll try to get to this tomorrow. but if you want to toss this off the renderer thread look at ipc-events.ts

**Comment by grimothy-the-reaper** [comment]
This looks really good. One suggestion and one possible bug.
**Suggestion**: Have a button to open the directory of the back. This would help when someone has multiple PCs with the WoWUp software.
**Possible Bug**: Creating a backup activates the "Restore" button properly. Removing the last backup does not de-active the "Restore" button.

**Comment by ayell** [comment]
@grimothy-the-reaper I saw that bug ^^ , I check only if my custom folder exist, and not if is empty . i will fix that this afternoon :)
I dont understand why do you want I create a button to open the folder ? I think its better if the user dont touch the folder outisde the app .

@jliddev  I see the ipc-events.ts but I have a problem ... I have not problem with the 'freeze' on the app during the zip/unzip process, so the user does not risk adding or removing addons during the process. However I display the snacbkar before the creation of the AdmZip object but it goes too fast and it starts to zip before displaying the message. The only solution that I found is to move the action 1 second.

**Comment by ayell** [comment]
I fix the state of restore button :)

**Comment by grimothy-the-reaper** [comment]
> I dont understand why do you want I create a button to open the folder ? I think its better if the user dont touch the folder outisde the app .

@ayell There's no way to sync addons between two different PCs. Exporting from computer A, copying the file to computer B, then importing on computer B is the best option right now.

**Comment by ayell** [comment]
@grimothy-the-reaper I have in my plan , to implement dropbox/google drive API to backup in own our cloud . I dont think it's a good idea to manage manually the backups

**Comment by ayell** [comment]
Why closed ? :/

**Comment by linaori** [comment]
The closing of this issue happened because the electron branch has been removed. Is it possible to change your branch to `develop` and make a new PR with your changes?

**Comment by ayell** [comment]
if @jliddev whant this feature I can do this ...

**Comment by jliddev** [comment]
rebase to develop and reopen

**Pull request closed without merging**
